version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/app" 
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 100
    ignore:
      - dependency-name: "*" 
        update-types: ["version-update:semver-patch"]

  - package-ecosystem: "pip"
    directory: "/app" 
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows" 
    schedule:
      interval: "weekly"
