version: "3"
services:
  omslagroute:
    image: ${REGISTRY:-127.0.0.1:5001}/${REPOSITORY:-salmagundi/wonen-omslagroute}:${VERSION:-latest}
    build:
      dockerfile: Dockerfile
      context: app
    container_name: salmagundi_wonen_omslagroute
    ports:
      - "127.0.0.1:8088:8080"
    environment:
      - DATABASE_NAME=omslagroute
      - DATABASE_USER=salmagundi
      - DATABASE_PASSWORD=insecure
      - DATABASE_HOST=psql-postgresql