# Generated by Django 2.2.13 on 2022-03-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0038_auto_20200821_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='partner_emailadres',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='partner E-mailadres'),
        ),
        migrations.AddField(
            model_name='caseversion',
            name='partner_emailadres',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='partner E-mailadres'),
        ),
    ]
