# Generated by Django 5.0.8 on 2025-02-05 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0039_auto_20220322_1456'),
        ('profiles', '0003_auto_20200325_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='adres_stadsdeel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Stadsdeel'),
        ),
        migrations.AddField(
            model_name='caseversion',
            name='adres_stadsdeel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Stadsdeel'),
        ),
        migrations.AlterField(
            model_name='case',
            name='woningcorporatie_medewerker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='profiles.profile', verbose_name='Woningcorporatie medewerker'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='woningcorporatie_medewerker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='profiles.profile', verbose_name='Woningcorporatie medewerker'),
        ),
    ]
