# Generated by Django 5.0.8 on 2025-02-15 18:53

import multiselectfield.db.fields
import web.cases.models
import web.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0040_add_stadsdeel'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='match_woning_informatie_delen',
            field=models.BooleanField(blank=True, null=True, verbose_name='Ik deel als zorgaanbieder deze informatie met de woningcorporatie.'),
        ),
        migrations.AddField(
            model_name='caseversion',
            name='match_woning_informatie_delen',
            field=models.BooleanField(blank=True, null=True, verbose_name='Ik deel als zorgaanbieder deze informatie met de woningcorporatie.'),
        ),
        migrations.AlterField(
            model_name='document',
            name='forms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('aanvraag-omslag-en-urgentie', 'Aanvraag Urgentie onder voorwaarden'), ('aanvraag-omklap', 'Aanvraag Voordracht omklap'), ('evaluatie-wonen', 'Evaluatie wonen'), ('match-met-passende-woning', 'Match met passende woning'), ('kennismaking-woningcorporatie', 'Kennismaking woningcorporatie')], max_length=115, null=True, verbose_name='Formulieren'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_file',
            field=models.FileField(upload_to=web.cases.models.get_upload_path, validators=[web.core.utils.validate_uploaded_file], verbose_name='Selecteer een bestand'),
        ),
    ]
