# Generated by Django 5.2.14 on 2026-06-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0041_add_match_passende_woning"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="kennismaking_wooncorporatie_akkoord_zorgaanbieder_telefoonnummer",
            field=models.CharField(
                blank=True,
                db_column="kw_akkoord_za_telefoonnummer",
                max_length=20,
                null=True,
                verbose_name="Telefoonnummer zorgaanbieder",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="persoonlijk_begeleider_telefoonnummer",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Telefoonnummer persoonlijk begeleider",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="woonevaluatie_akkoord_zorgaanbieder_telefoonnummer",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Telefoonnummer zorgaanbieder",
            ),
        ),
        migrations.AddField(
            model_name="caseversion",
            name="kennismaking_wooncorporatie_akkoord_zorgaanbieder_telefoonnummer",
            field=models.CharField(
                blank=True,
                db_column="kw_akkoord_za_telefoonnummer",
                max_length=20,
                null=True,
                verbose_name="Telefoonnummer zorgaanbieder",
            ),
        ),
        migrations.AddField(
            model_name="caseversion",
            name="persoonlijk_begeleider_telefoonnummer",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Telefoonnummer persoonlijk begeleider",
            ),
        ),
        migrations.AddField(
            model_name="caseversion",
            name="woonevaluatie_akkoord_zorgaanbieder_telefoonnummer",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Telefoonnummer zorgaanbieder",
            ),
        ),
    ]
