image:
  registry: 127.0.0.1:5001
  imagePullPolicy: Always

host: omslagroute.local

securityContext:
  container:
    readOnlyRootFilesystem: false

secrets:
  certificate:
    enabled: false
  vault:
    enabled: false

deployments:
  wonen-omslagroute:
    image:
      repository: salmagundi/wonen-omslagroute
    selectorLabels:
      component: omslagroute
    env:
      APP_ENV: dev
      DATABASE_NAME: omslagroute
      DATABASE_USER: salmagundi
      DATABASE_PASSWORD: insecure
      DATABASE_HOST: psql-postgresql
    containers:
      - name: main
        ports:
          - port: 8080
            name: http
        secrets: []

services:
  wonen-omslagroute:
    selector:
      component: omslagroute
    ports:
      - port: 8080
        targetPort: http

ingress:
  wonen-omslagroute-internal:
    className: nginx
    paths:
      - path: /
        pathType: Prefix
        service: wonen-omslagroute
        port: 8080

jobs:
  certificate-init:
    enabled: false
