# Generated by Django 3.2 on 2023-09-18 14:20

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20230301_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Redactie'), (2, 'Wonen medewerker'), (4, 'Woningcorporatie medewerker'), (5, 'Persoonlijk begeleider'), (6, 'Onbekend/inactief'), (7, 'Beheerder'), (8, 'Organisatie beheerder'), (9, 'PB & Organisatie beheerder')], default=[6], max_length=15, verbose_name='Gebruiker rol'),
        ),
    ]
